import { v4 as uuidv4 } from 'uuid';

import img1 from '../assets/top-selling/img-1.png';
import img2 from '../assets/top-selling/img-2.png';
import img3 from '../assets/top-selling/img-3.png';
import img4 from '../assets/top-selling/img-4.png';
import img5 from '../assets/top-selling/img-5.png';
import img6 from '../assets/top-selling/img-6.png';
import img7 from '../assets/top-selling/img-7.png';

const topSelling = [
  {
    id: uuidv4(),
    img: img1,
    title: 'Vertical Striped Shirt',
    sizes: ['Small', 'Medium', 'Large', 'X-Large'],
    color: ['Green', 'Black', 'Grey'],
    rating: 5,
    newPrice: 212,
    oldPrice: 232,
    discount: '-20%',
    reviews: [
      {
        id: uuidv4(),
        rating: 5,
        user: 'Samantha D.',
        comment: `"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. It's become my favorite go-to shirt."`,
        posted: 'Posted on August 14, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Alex M.',
        comment: `"The t-shirt exceeded my expectations! The colors are vibrant and the print quality is top-notch. Being a UI/UX designer myself, I'm quite picky about aesthetics, and this t-shirt definitely gets a thumbs up from me."`,
        posted: 'Posted on August 15, 2023',
      },
      {
        id: uuidv4(),
        rating: 3.5,
        user: 'Ethan R.',
        comment: `"This t-shirt is a must-have for anyone who appreciates good design. The minimalistic yet stylish pattern caught my eye, and the fit is perfect. I can see the designer's touch in every aspect of this shirt."`,
        posted: 'Posted on August 16, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Olivia P.',
        comment: `"As a UI/UX enthusiast, I value simplicity and functionality. This t-shirt not only represents those principles but also feels great to wear. It's evident that the designer poured their creativity into making this t-shirt stand out."`,
        posted: 'Posted on August 17, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Liam K.',
        comment: `"This t-shirt is a fusion of comfort and creativity. The fabric is soft, and the design speaks volumes about the designer's skill. It's like wearing a piece of art that reflects my passion for both design and fashion."`,
        posted: 'Posted on August 18, 2023',
      },
      {
        id: uuidv4(),
        rating: 4.5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 19, 2023',
      },
      {
        id: uuidv4(),
        rating: 5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 19, 2024',
      },
      {
        id: uuidv4(),
        rating: 5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 20, 2024',
      },
    ],
  },
  {
    id: uuidv4(),
    img: img2,
    title: 'Courage Graphic T-shirt',
    sizes: ['Small', 'Medium', 'Large', 'X-Large'],
    color: ['Green', 'Black', 'Grey'],
    rating: 4,
    newPrice: 145,
    reviews: [
      {
        id: uuidv4(),
        rating: 5,
        user: 'Samantha D.',
        comment: `"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. It's become my favorite go-to shirt."`,
        posted: 'Posted on August 14, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Alex M.',
        comment: `"The t-shirt exceeded my expectations! The colors are vibrant and the print quality is top-notch. Being a UI/UX designer myself, I'm quite picky about aesthetics, and this t-shirt definitely gets a thumbs up from me."`,
        posted: 'Posted on August 15, 2023',
      },
      {
        id: uuidv4(),
        rating: 3.5,
        user: 'Ethan R.',
        comment: `"This t-shirt is a must-have for anyone who appreciates good design. The minimalistic yet stylish pattern caught my eye, and the fit is perfect. I can see the designer's touch in every aspect of this shirt."`,
        posted: 'Posted on August 16, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Olivia P.',
        comment: `"As a UI/UX enthusiast, I value simplicity and functionality. This t-shirt not only represents those principles but also feels great to wear. It's evident that the designer poured their creativity into making this t-shirt stand out."`,
        posted: 'Posted on August 17, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Liam K.',
        comment: `"This t-shirt is a fusion of comfort and creativity. The fabric is soft, and the design speaks volumes about the designer's skill. It's like wearing a piece of art that reflects my passion for both design and fashion."`,
        posted: 'Posted on August 18, 2023',
      },
      {
        id: uuidv4(),
        rating: 4.5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 19, 2023',
      },
      {
        id: uuidv4(),
        rating: 5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 19, 2024',
      },
      {
        id: uuidv4(),
        rating: 5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 20, 2024',
      },
    ],
  },
  {
    id: uuidv4(),
    img: img3,
    title: 'Loose Fit Bermuda Shorts',
    sizes: ['Small', 'Medium', 'Large', 'X-Large'],
    color: ['Green', 'Black', 'Grey'],
    rating: 3,
    newPrice: 80,
    reviews: [
      {
        id: uuidv4(),
        rating: 5,
        user: 'Samantha D.',
        comment: `"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. It's become my favorite go-to shirt."`,
        posted: 'Posted on August 14, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Alex M.',
        comment: `"The t-shirt exceeded my expectations! The colors are vibrant and the print quality is top-notch. Being a UI/UX designer myself, I'm quite picky about aesthetics, and this t-shirt definitely gets a thumbs up from me."`,
        posted: 'Posted on August 15, 2023',
      },
      {
        id: uuidv4(),
        rating: 3.5,
        user: 'Ethan R.',
        comment: `"This t-shirt is a must-have for anyone who appreciates good design. The minimalistic yet stylish pattern caught my eye, and the fit is perfect. I can see the designer's touch in every aspect of this shirt."`,
        posted: 'Posted on August 16, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Olivia P.',
        comment: `"As a UI/UX enthusiast, I value simplicity and functionality. This t-shirt not only represents those principles but also feels great to wear. It's evident that the designer poured their creativity into making this t-shirt stand out."`,
        posted: 'Posted on August 17, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Liam K.',
        comment: `"This t-shirt is a fusion of comfort and creativity. The fabric is soft, and the design speaks volumes about the designer's skill. It's like wearing a piece of art that reflects my passion for both design and fashion."`,
        posted: 'Posted on August 18, 2023',
      },
      {
        id: uuidv4(),
        rating: 4.5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 19, 2023',
      },
      {
        id: uuidv4(),
        rating: 5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 19, 2024',
      },
      {
        id: uuidv4(),
        rating: 5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 20, 2024',
      },
    ],
  },
  {
    id: uuidv4(),
    img: img4,
    title: 'Faded Skinny Jeans',
    sizes: ['Small', 'Medium', 'Large', 'X-Large'],
    color: ['Green', 'Black', 'Grey'],
    rating: 4.5,
    newPrice: 210,
    reviews: [
      {
        id: uuidv4(),
        rating: 5,
        user: 'Samantha D.',
        comment: `"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. It's become my favorite go-to shirt."`,
        posted: 'Posted on August 14, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Alex M.',
        comment: `"The t-shirt exceeded my expectations! The colors are vibrant and the print quality is top-notch. Being a UI/UX designer myself, I'm quite picky about aesthetics, and this t-shirt definitely gets a thumbs up from me."`,
        posted: 'Posted on August 15, 2023',
      },
      {
        id: uuidv4(),
        rating: 3.5,
        user: 'Ethan R.',
        comment: `"This t-shirt is a must-have for anyone who appreciates good design. The minimalistic yet stylish pattern caught my eye, and the fit is perfect. I can see the designer's touch in every aspect of this shirt."`,
        posted: 'Posted on August 16, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Olivia P.',
        comment: `"As a UI/UX enthusiast, I value simplicity and functionality. This t-shirt not only represents those principles but also feels great to wear. It's evident that the designer poured their creativity into making this t-shirt stand out."`,
        posted: 'Posted on August 17, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Liam K.',
        comment: `"This t-shirt is a fusion of comfort and creativity. The fabric is soft, and the design speaks volumes about the designer's skill. It's like wearing a piece of art that reflects my passion for both design and fashion."`,
        posted: 'Posted on August 18, 2023',
      },
      {
        id: uuidv4(),
        rating: 4.5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 19, 2023',
      },
      {
        id: uuidv4(),
        rating: 5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 19, 2024',
      },
      {
        id: uuidv4(),
        rating: 5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 20, 2024',
      },
    ],
  },
  {
    id: uuidv4(),
    img: img5,
    title: 'Polo with Tipping Details',
    sizes: ['Small', 'Medium', 'Large', 'X-Large'],
    color: ['Green', 'Black', 'Grey'],
    rating: 4.5,
    newPrice: 180,
    reviews: [
      {
        id: uuidv4(),
        rating: 5,
        user: 'Samantha D.',
        comment: `"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. It's become my favorite go-to shirt."`,
        posted: 'Posted on August 14, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Alex M.',
        comment: `"The t-shirt exceeded my expectations! The colors are vibrant and the print quality is top-notch. Being a UI/UX designer myself, I'm quite picky about aesthetics, and this t-shirt definitely gets a thumbs up from me."`,
        posted: 'Posted on August 15, 2023',
      },
      {
        id: uuidv4(),
        rating: 3.5,
        user: 'Ethan R.',
        comment: `"This t-shirt is a must-have for anyone who appreciates good design. The minimalistic yet stylish pattern caught my eye, and the fit is perfect. I can see the designer's touch in every aspect of this shirt."`,
        posted: 'Posted on August 16, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Olivia P.',
        comment: `"As a UI/UX enthusiast, I value simplicity and functionality. This t-shirt not only represents those principles but also feels great to wear. It's evident that the designer poured their creativity into making this t-shirt stand out."`,
        posted: 'Posted on August 17, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Liam K.',
        comment: `"This t-shirt is a fusion of comfort and creativity. The fabric is soft, and the design speaks volumes about the designer's skill. It's like wearing a piece of art that reflects my passion for both design and fashion."`,
        posted: 'Posted on August 18, 2023',
      },
      {
        id: uuidv4(),
        rating: 4.5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 19, 2023',
      },
      {
        id: uuidv4(),
        rating: 5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 19, 2024',
      },
      {
        id: uuidv4(),
        rating: 5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 20, 2024',
      },
    ],
  },
  {
    id: uuidv4(),
    img: img6,
    title: 'Black Striped T-shirt',
    sizes: ['Small', 'Medium', 'Large', 'X-Large'],
    color: ['Green', 'Black', 'Grey'],
    rating: 5,
    newPrice: 120,
    reviews: [
      {
        id: uuidv4(),
        rating: 5,
        user: 'Samantha D.',
        comment: `"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. It's become my favorite go-to shirt."`,
        posted: 'Posted on August 14, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Alex M.',
        comment: `"The t-shirt exceeded my expectations! The colors are vibrant and the print quality is top-notch. Being a UI/UX designer myself, I'm quite picky about aesthetics, and this t-shirt definitely gets a thumbs up from me."`,
        posted: 'Posted on August 15, 2023',
      },
      {
        id: uuidv4(),
        rating: 3.5,
        user: 'Ethan R.',
        comment: `"This t-shirt is a must-have for anyone who appreciates good design. The minimalistic yet stylish pattern caught my eye, and the fit is perfect. I can see the designer's touch in every aspect of this shirt."`,
        posted: 'Posted on August 16, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Olivia P.',
        comment: `"As a UI/UX enthusiast, I value simplicity and functionality. This t-shirt not only represents those principles but also feels great to wear. It's evident that the designer poured their creativity into making this t-shirt stand out."`,
        posted: 'Posted on August 17, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Liam K.',
        comment: `"This t-shirt is a fusion of comfort and creativity. The fabric is soft, and the design speaks volumes about the designer's skill. It's like wearing a piece of art that reflects my passion for both design and fashion."`,
        posted: 'Posted on August 18, 2023',
      },
      {
        id: uuidv4(),
        rating: 4.5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 19, 2023',
      },
      {
        id: uuidv4(),
        rating: 5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 19, 2024',
      },
      {
        id: uuidv4(),
        rating: 5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 20, 2024',
      },
    ],
  },
  {
    id: uuidv4(),
    img: img7,
    title: 'One Life Graphic T-shirt',
    about:
      'This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.',
    sizes: ['Small', 'Medium', 'Large', 'X-Large'],
    color: ['Green', 'Black', 'Grey'],
    rating: 5,
    newPrice: 260,
    oldPrice: 300,
    discount: '-40%',
    reviews: [
      {
        id: uuidv4(),
        rating: 5,
        user: 'Samantha D.',
        comment: `"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. It's become my favorite go-to shirt."`,
        posted: 'Posted on August 14, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Alex M.',
        comment: `"The t-shirt exceeded my expectations! The colors are vibrant and the print quality is top-notch. Being a UI/UX designer myself, I'm quite picky about aesthetics, and this t-shirt definitely gets a thumbs up from me."`,
        posted: 'Posted on August 15, 2023',
      },
      {
        id: uuidv4(),
        rating: 3.5,
        user: 'Ethan R.',
        comment: `"This t-shirt is a must-have for anyone who appreciates good design. The minimalistic yet stylish pattern caught my eye, and the fit is perfect. I can see the designer's touch in every aspect of this shirt."`,
        posted: 'Posted on August 16, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Olivia P.',
        comment: `"As a UI/UX enthusiast, I value simplicity and functionality. This t-shirt not only represents those principles but also feels great to wear. It's evident that the designer poured their creativity into making this t-shirt stand out."`,
        posted: 'Posted on August 17, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Liam K.',
        comment: `"This t-shirt is a fusion of comfort and creativity. The fabric is soft, and the design speaks volumes about the designer's skill. It's like wearing a piece of art that reflects my passion for both design and fashion."`,
        posted: 'Posted on August 18, 2023',
      },
      {
        id: uuidv4(),
        rating: 4.5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 19, 2023',
      },
      {
        id: uuidv4(),
        rating: 5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 19, 2024',
      },
      {
        id: uuidv4(),
        rating: 5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 20, 2024',
      },
    ],
  },
  {
    id: uuidv4(),
    img: img1,
    title: 'Vertical Striped Shirt',
    sizes: ['Small', 'Medium', 'Large', 'X-Large'],
    color: ['Green', 'Black', 'Grey'],
    rating: 4,
    newPrice: 210,
    reviews: [
      {
        id: uuidv4(),
        rating: 5,
        user: 'Samantha D.',
        comment: `"I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable. As a fellow designer, I appreciate the attention to detail. It's become my favorite go-to shirt."`,
        posted: 'Posted on August 14, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Alex M.',
        comment: `"The t-shirt exceeded my expectations! The colors are vibrant and the print quality is top-notch. Being a UI/UX designer myself, I'm quite picky about aesthetics, and this t-shirt definitely gets a thumbs up from me."`,
        posted: 'Posted on August 15, 2023',
      },
      {
        id: uuidv4(),
        rating: 3.5,
        user: 'Ethan R.',
        comment: `"This t-shirt is a must-have for anyone who appreciates good design. The minimalistic yet stylish pattern caught my eye, and the fit is perfect. I can see the designer's touch in every aspect of this shirt."`,
        posted: 'Posted on August 16, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Olivia P.',
        comment: `"As a UI/UX enthusiast, I value simplicity and functionality. This t-shirt not only represents those principles but also feels great to wear. It's evident that the designer poured their creativity into making this t-shirt stand out."`,
        posted: 'Posted on August 17, 2023',
      },
      {
        id: uuidv4(),
        rating: 4,
        user: 'Liam K.',
        comment: `"This t-shirt is a fusion of comfort and creativity. The fabric is soft, and the design speaks volumes about the designer's skill. It's like wearing a piece of art that reflects my passion for both design and fashion."`,
        posted: 'Posted on August 18, 2023',
      },
      {
        id: uuidv4(),
        rating: 4.5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 19, 2023',
      },
      {
        id: uuidv4(),
        rating: 5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 19, 2024',
      },
      {
        id: uuidv4(),
        rating: 5,
        user: 'Ava H.',
        comment: `"I'm not just wearing a t-shirt; I'm wearing a piece of design philosophy. The intricate details and thoughtful layout of the design make this shirt a conversation starter."`,
        posted: 'Posted on August 20, 2024',
      },
    ],
  },
];

export default topSelling;
